In [3]:
import pandas as pd
df = pd.read_parquet("datamart/gold/feature_store/part-00227-6d63faf2-25c6-4987-8bfb-9c37eaef13de-c000.snappy.parquet", engine="pyarrow")
df.head(10)

,Customer_ID,feature_snapshot_date,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Utilization_Ratio,...,fe_11,fe_12,fe_13,fe_14,fe_15,fe_16,fe_17,fe_18,fe_19,fe_20
0,CUS_0x10dd,2024-06-01,4.0,3.0,5.0,28,19.0,2.41,4.0,40.455482,...,49.0,195.0,-23.0,29.0,40.0,122.0,232.0,166.0,60.0,262.0
1,CUS_0x1109,2024-06-01,6.0,10.0,18.0,24,12.0,6.69,11.0,29.364434,...,127.0,172.0,120.0,236.0,238.0,103.0,135.0,-9.0,242.0,-47.0
2,CUS_0x1286,2024-06-01,7.0,3.0,12.0,22,8.0,0.14,8.0,32.073869,...,75.0,140.0,95.0,118.0,73.0,-131.0,113.0,53.0,81.0,236.0
3,CUS_0x12a8,2024-06-01,3.0,6.0,10.0,22,15.0,15.53,4.0,39.791529,...,195.0,-84.0,258.0,46.0,-36.0,107.0,191.0,-48.0,123.0,143.0
4,CUS_0x1309,2024-06-01,4.0,5.0,12.0,21,20.0,8.24,4.0,32.777618,...,203.0,143.0,258.0,134.0,114.0,126.0,258.0,87.0,151.0,198.0
5,CUS_0x13f8,2024-06-01,5.0,4.0,7.0,0,6.0,5.91,1.0,39.010395,...,-54.0,193.0,91.0,228.0,-30.0,140.0,154.0,227.0,-188.0,108.0
6,CUS_0x1472,2024-06-01,3.0,4.0,13.0,10,9.0,16.95,9.0,34.679209,...,118.0,61.0,166.0,-56.0,65.0,11.0,258.0,156.0,74.0,71.0
7,CUS_0x15a3,2024-06-01,1.0,3.0,5.0,6,8.0,-3.50,3.0,27.120114,...,99.0,89.0,155.0,168.0,131.0,182.0,222.0,155.0,152.0,174.0
8,CUS_0x15f4,2024-06-01,6.0,4.0,10.0,15,20.0,15.44,5.0,37.130051,...,134.0,4.0,23.0,230.0,50.0,146.0,76.0,172.0,154.0,-71.0
9,CUS_0x15f8,2024-06-01,6.0,5.0,10.0,21,8.0,8.42,4.0,40.276293,...,217.0,72.0,-119.0,-13.0,34.0,153.0,153.0,197.0,-11.0,184.0

In [4]:
df.columns

Index(['Customer_ID', 'feature_snapshot_date', 'Num_Bank_Accounts',
       'Num_Credit_Card', 'Interest_Rate', 'Delay_from_due_date',
       'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Credit_Utilization_Ratio', 'Monthly_Balance',
       'credit_history_months', 'num_loan_types', 'log_Annual_Income',
       'debt_to_income', 'emi_to_salary', 'investment_rate',
       'has_credit_limit_change', 'balance_to_debt', 'inq_per_loan',
       'Credit_Mix_vec', 'Payment_Behaviour_vec', 'Payment_of_Min_Amount_vec',
       'Occupation_vec', 'Age_group_vec', 'fe_1', 'fe_2', 'fe_3', 'fe_4',
       'fe_5', 'fe_6', 'fe_7', 'fe_8', 'fe_9', 'fe_10', 'fe_11', 'fe_12',
       'fe_13', 'fe_14', 'fe_15', 'fe_16', 'fe_17', 'fe_18', 'fe_19', 'fe_20'],
      dtype='object')

In [5]:
import pandas as pd
df = pd.read_parquet("datamart/gold/label_store/part-00011-4b373f01-42d3-4568-affc-6aaa5d7b9fbb-c000.snappy.parquet", engine="pyarrow")
df.head(10)

  Customer_ID                loan_id  label snapshot_date
0  CUS_0x503f  CUS_0x503f_2025_01_01      0    2025-07-01
1  CUS_0x50af  CUS_0x50af_2025_01_01      0    2025-07-01
2  CUS_0x512d  CUS_0x512d_2025_01_01      0    2025-07-01
3  CUS_0x51de  CUS_0x51de_2025_01_01      0    2025-07-01
4  CUS_0x526a  CUS_0x526a_2025_01_01      0    2025-07-01
5  CUS_0x52c3  CUS_0x52c3_2025_01_01      0    2025-07-01
6  CUS_0x5313  CUS_0x5313_2025_01_01      0    2025-07-01
7  CUS_0x532a  CUS_0x532a_2025_01_01      0    2025-07-01
8  CUS_0x533e  CUS_0x533e_2025_01_01      1    2025-07-01
9  CUS_0x5352  CUS_0x5352_2025_01_01      0    2025-07-01