In [1]:
import pandas as pd

In [3]:
pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-22.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.2 kB)
Downloading pyarrow-22.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (47.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.7/47.7 MB 2.1 MB/s eta 0:00:0000:0100:01
Installing collected packages: pyarrow
Successfully installed pyarrow-22.0.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [12]:
import pyarrow.dataset as ds

folder = "/app/datamart/gold/feature_store/feature_store_2024-12-01.parquet"  # pick any month
dataset = ds.dataset(folder, format="parquet")   # handles part-*.parquet inside
df = dataset.to_table().to_pandas()
df.head(10)

,Customer_ID,Name,Age,SSN,Occupation,snapshot_date,_ingested_at_utc,feat_balance,feat_utilization_bucket,feat_trades_open
0,CUS_0x0000,User0,18,100-10-1000,Engineer,2024-12-01,2024-12-01,869,4,9
1,CUS_0x0001,User1,19,101-11-1001,Teacher,2024-12-01,2024-12-01,320,0,0
2,CUS_0x0002,User2,20,102-12-1002,Doctor,2024-12-01,2024-12-01,377,2,9
3,CUS_0x0003,User3,21,103-13-1003,Clerk,2024-12-01,2024-12-01,20,0,0
4,CUS_0x0004,User4,22,104-14-1004,Artist,2024-12-01,2024-12-01,42,2,2
5,CUS_0x0005,User5,23,105-15-1005,Unknown,2024-12-01,2024-12-01,620,0,8
6,CUS_0x0006,User6,24,106-16-1006,Engineer,2024-12-01,2024-12-01,116,1,0
7,CUS_0x0007,User7,25,107-17-1007,Teacher,2024-12-01,2024-12-01,760,0,4
8,CUS_0x0008,User8,26,108-18-1008,Doctor,2024-12-01,2024-12-01,568,3,0
9,CUS_0x0009,User9,27,109-19-1009,Clerk,2024-12-01,2024-12-01,475,0,11

In [13]:
import pyarrow.dataset as ds

folder = "/app/datamart/gold/label_store/gold_label_store_2024-12-01.parquet"  # pick any month
dataset = ds.dataset(folder, format="parquet")   # handles part-*.parquet inside
df = dataset.to_table().to_pandas()
df.head(10)

                 loan_id Customer_ID  label   label_def snapshot_date
0  CUS_0x0000_2024-12-01  CUS_0x0000      0  30dpd_6mob    2025-06-01
1  CUS_0x0001_2024-12-01  CUS_0x0001      1  30dpd_6mob    2025-06-01
2  CUS_0x0002_2024-12-01  CUS_0x0002      0  30dpd_6mob    2025-06-01
3  CUS_0x0003_2024-12-01  CUS_0x0003      0  30dpd_6mob    2025-06-01
4  CUS_0x0004_2024-12-01  CUS_0x0004      0  30dpd_6mob    2025-06-01
5  CUS_0x0005_2024-12-01  CUS_0x0005      0  30dpd_6mob    2025-06-01
6  CUS_0x0006_2024-12-01  CUS_0x0006      0  30dpd_6mob    2025-06-01
7  CUS_0x0007_2024-12-01  CUS_0x0007      0  30dpd_6mob    2025-06-01
8  CUS_0x0008_2024-12-01  CUS_0x0008      1  30dpd_6mob    2025-06-01
9  CUS_0x0009_2024-12-01  CUS_0x0009      0  30dpd_6mob    2025-06-01